name    'torian-hosts'
version '0.0.1'
source 'https://github.com/torian/puppet-hosts'
author 'Emiliano Castagnari ecastag@gmail.com (aka Torian)'
license 'GPL v2'
summary 'hosts module for Puppet.'
description 'Manage hosts file via Puppet'
project_page 'https://github.com/torian/puppet-hosts'
